databases:
  - name: atoz
    user: atoz
    plan: free
    region: ohio

services:
  - type: web
    name: atoz
    plan: free
    region: ohio
    branch: main
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: atoz
          property: connectionString
      - key: c5ce230f43a889f44591c9aaa032ce44s
        sync: false